using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
namespace General_Manager.Form
{
    public partial class Schedule : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public Schedule()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            employeeTableAdapter1.Fill(hotel_ManagementDataSet1.Employee);
        }
        void navBarControl_ActiveGroupChanged(object sender, DevExpress.XtraNavBar.NavBarGroupEventArgs e)
        {
            navigationFrame.SelectedPageIndex = navBarControl.Groups.IndexOf(e.Group);
        }
        void barButtonNavigation_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            int barItemIndex = barSubItemNavigation.ItemLinks.IndexOf(e.Link);
            navBarControl.ActiveGroup = navBarControl.Groups[barItemIndex];
        }
        public void GetNumber()
        {
            EmployeeHotel user = new EmployeeHotel();
            WorkShift w = new WorkShift();
            double manager = Convert.ToDouble(user.GetNumberOfManager());
            Getnum.Text = "Manager: " + manager.ToString();

        }

        private void Schedule_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'hotel_ManagementDataSet11.Schedule' table. You can move, or remove it, as needed.
            this.scheduleTableAdapter.Fill(this.hotel_ManagementDataSet11.Schedule);
            this.ShiftWork();
            WorkShift s = new WorkShift();
            s.DeleteData();
            s.InsertShift();
            this.GetNumber();
        }
        public void ShiftWork()
        {
            WorkShift w = new WorkShift();
            GridControl_DisplayShift.DataSource = w.ShowShift();
        }

        private void Setshift_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            WorkShift w = new WorkShift();
            GridControl_DisplayShift.DataSource = w.ShowReloadShift();
           
        }

        private void RibbonControl_SelectedPageChanged(object sender, EventArgs e)
        {
            switch (RibbonControl.SelectedPage.Name)
            {
                case "GridControlData":
                    DocumentViewer_DataShift.Visible = false;
                    GridControl_DisplayShift.Visible = true;
                    break;
                case "PreviewRibbonPage":
                    GridControl_DisplayShift.Visible = false;
                    DocumentViewer_DataShift.Visible = true;
                    printableComponentLink1.CreateDocument();
                    break;
            }
        }

        private void BarFind_btn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            gridView1.OptionsFind.AlwaysVisible = true;
        }

        private void BarCardView_btn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            cardView1.ShowFindPanel();
        }

        private void RemoveSchedule_btn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            WorkShift s = new WorkShift();
            s.DeleteData();
            s.InsertShift();
            GridControl_DisplayShift.DataSource = s.ShowShift();
        }
    }
}