//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_in
    {
        public System.DateTime check_in_date { get; set; }
        public int emp_id { get; set; }
        public Nullable<System.TimeSpan> check_in_time { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Check_out Check_out { get; set; }
    }
}
