//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Check_in = new HashSet<Check_in>();
            this.Check_out = new HashSet<Check_out>();
            this.Manage_emp = new HashSet<Manage_emp>();
            this.Monney_Transaction = new HashSet<Monney_Transaction>();
            this.Positions = new HashSet<Position>();
        }
    
        public int Id { get; set; }
        public string password { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string address { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> daywork { get; set; }
        public Nullable<int> work { get; set; }
        public byte[] picture { get; set; }
        public string gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check_in> Check_in { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check_out> Check_out { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manage_emp> Manage_emp { get; set; }
        public virtual Manage_emp Manage_emp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monney_Transaction> Monney_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
    }
}
