//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hotel_Management_Entities : DbContext
    {
        public Hotel_Management_Entities()
            : base("name=Hotel_Management_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Check_in> Check_in { get; set; }
        public virtual DbSet<Check_out> Check_out { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Manage_emp> Manage_emp { get; set; }
        public virtual DbSet<Monney_Transaction> Monney_Transaction { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
    }
}
