//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monney_Transaction
    {
        public int id_transaction { get; set; }
        public string transaction_type { get; set; }
        public Nullable<System.DateTime> execute_date { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<decimal> money_tranfer { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
